version: "3.1"
services:
  postgres:
    image: postgres:latest
    container_name: postgres2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: security_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: